### ISSUE TITLE
Can you add scrapping libaries?

### ISSUE THREAD

**Issue by Sawanooo** [Zaczero/py-lib-collection#1]
Hello,

I was wondering, could you add scrapper libaries to it? Really useful information you've got here! :)

**Comment by Zaczero** [comment]
There is already a scraping library under the [HTTP section](https://github.com/Zaczero/py-lib-collection#http) called [Scrapy](https://pypi.org/project/Scrapy/).

I will add one or two more 👍.

_PS.
I am amazed that someone has decided to click on that repo within just 1 hour of its creation._

**Comment by Sawanooo** [comment]
> There is already a scraping library under the [HTTP section](https://github.com/Zaczero/py-lib-collection#http) called [Scrapy](https://pypi.org/project/Scrapy/).
> 
> I will add one or two more 👍.
> 
> _PS. I am amazed that someone has decided to click on that repo within just 1 hour of its creation._

I use some of your staff from like last few months. Been trying to get hold of you by email  :D 
Pretty great stuff you make, new to programing aswell!
